dist: xenial
arch:
  - amd64
  - ppc64le
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get install -qfy apertium-dev apertium-lex-tools cg3-dev gawk pkg-config
script:
  - ./autogen.sh
  - make -j2
  - make test
